version: "3.9"
services:
  #PostgreSQL
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=interim
    ports:
      - "5432:5432"
    volumes:
      - ./contrat.sql:/docker-entrypoint-initdb.d/contrat.sql