version: "3.9"
services:
  # PostgreSQL
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=contrat
    ports:
      - "5432:5432"
    volumes:
      - ./contrat.sql:/docker-entrypoint-initdb.d/contrat.sql

  # Spring Boot App
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: easycontrat-app
    ports:
      - "8081:8081"
    depends_on:
      - postgres